# Generated by Django 5.1.2 on 2024-11-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dinamic_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
