# Generated by Django 5.1.2 on 2024-11-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_dinamic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre url'),
        ),
    ]
